# Generated by Django 5.2.6 on 2026-05-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastry',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pastry',
            name='frosting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
