# Generated by Django 5.2.6 on 2026-04-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
