# Generated by Django 5.2.6 on 2026-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='confirmation_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
