# Generated by Django 5.2.6 on 2026-04-26 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Phone number must be exactly 8 digits')]),
        ),
    ]
