# Generated by Django 5.2.6 on 2026-05-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_full_name_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
